name: Scala Steward

on:
  workflow_call:
    secrets:
      APP_ID:
        description: 'GitHub App ID for authentication'
        required: true
      APP_INSTALLATION_ID:
        description: 'GitHub App Installation ID for authentication'
        required: true
      APP_PRIVATE_KEY:
        description: 'GitHub App Private Key for authentication'
        required: true
    inputs:
      scala-steward-version:
        description: 'Version of scala-steward-action to use'
        required: false
        type: string
        default: 'v2'

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - uses: scala-steward-org/scala-steward-action@${{ inputs.scala-steward-version }}
        with:
          github-app-auth-only: true
          github-app-id: ${{ secrets.APP_ID }}
          github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
